version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    image: ghizlanera/laravel-app:latest
    container_name: laravel-app
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge